# Exception Handling

## Throw

```js
function divide(a, b) {
  if (b === 0) {
    throw new Error("Division by zero is not allowed");
  }
  return a / b;
}
```

## Try...Catch...Finaly

```js
function readDataFromFile(filename) {
  let data;

  try {
    data = readFile(filename);
  } catch (error) {
    console.error("Error reading data:", error.message);
  } finally {
    closeFile(filename);
  }

  return data;
}
```

## Error Object

The Error object provides error information when an error occurs.

```js
try {
  adddlert("Welcome");
} catch (err) {
  document.getElementById("demo").innerHTML = err.name + "<br>" + err.message;
}
```

#### Properties

```js
err.name; // Sets or returns an error name
err.message; // Sets or returns an error message (a string)
```

#### Error Names

```js
RangeError; // A number "out of range" has occurred
ReferenceError; // An illegal reference has occurred
SyntaxError; // A syntax error has occurred
TypeError; // A type error has occurred
URIError; // An error in encodeURI() has occurred
```
